- id: jsonschema-gentypes
  name: Generate Python types based on TypedDict from a JSON schema
  entry: jsonschema-gentypes
  language: python
  pass_filenames: false
  files: ^jsonschema-gentypes.yaml$
  additional_dependencies:
    - pre-commit==3.2.0 # pypi
