strictness: veryhigh
max-line-length: 110

pylint:
  disable:
    - wrong-import-order
    - too-many-arguments
    - too-many-branches
    - too-many-locals
    - too-many-statements
    - too-many-nested-blocks
    - too-many-return-statements
    - too-few-public-methods
    - no-else-return
    - line-too-long

pep8:
  disable:
    - E203 # whitespace before ':'
    - E501 # line too long

mypy:
  run: true

mccabe:
  run: false
