inherits:
  - duplicated
  - utils:base
  - utils:fix
  - utils:no-design-checks

ignore-patterns:
  - jsonschema_gentypes/configuration.py
  - jsonschema_gentypes/jsonschema_draft_.*\.py

bandit:
  options:
    config: .bandit.yaml
